fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|h|hpp|hxx)$
  - repo: local
    hooks:
      - id: docs format
        name: docs format
        entry: yarn --cwd docs format
        language: system
        files: ^docs/
        pass_filenames: false
      - id: docs-format-check
        name: docs format check
        entry: yarn --cwd docs format:check
        language: system
        files: ^docs/
        pass_filenames: false
      - id: docs-lint
        name: docs lint
        entry: yarn --cwd docs lint
        language: system
        files: ^docs/
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]